title: Blog Jhonathan Ribeiro
description: > # this means to ignore newlines until "baseurl:"
  Bem vindo ao meu blog! Aqui você encontra artigos sobre tecnologia, dicas, snippets e muito mais. Inscreva-se agora mesmo em nossa Newsletter e fique por dentro de todas as nossas novidades.
facebook: Jhonathanjbr
github:  JhonathanRibeiro
instagram: jhonathanrjb
twitter: Jhonathanjbr
linkedin: jhonathan-ribeiro
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jhonathan Ribeiro # add your name
author-img: jhonathan.png # add your photo
about-author: Sou desenvolvedor web focado no desenvolvimento front-end. Entusiasta de novas tecnologias Web e Mobile.

# Disqus
discus-identifier: Jhonathan Ribeiro # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
