title: Blog Jhonathan Ribeiro - Tecnologia | Webdesign | Marketing Digital
description: Aprenda mais sobre Webdesign,Marketing Digital e fique sempre atualizado com os principais assuntos da tecnologia.
facebook: Jhonathanjbr
github:  JhonathanRibeiro
instagram: jhonathan.rb
twitter: Jhonathanjbr
linkedin: jhonathan-ribeiro
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jhonathanribeiro.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jhonathan Ribeiro # add your name
author-img: jhonathan.jpg # add your photo
img-openGraph: woman-using-notebook-for-home-working.jpg
about-author: Sou desenvolvedor web focado no desenvolvimento front-end. Entusiasta de novas tecnologias Web e Mobile.

#Agency reference
agency-txt:   Webdesign Premium
agency-link:  https://jhonathanribeiro.github.io//
agency-title: Precisando de um site?

# Disqus
discus-identifier: Jhonathan Ribeiro # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

gems: 
 - jekyll-sitemap

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
  projects: