title: Blog Jhonathan Ribeiro. Tecnologia,Finanças,Dicas e muito mais.
description: Bem vindo(a) ao meu blog! Aqui você encontra artigos sobre tecnologia, finanças e muito mais.
facebook: Jhonathanjbr
github:  JhonathanRibeiro
instagram: jhonathan.rb
twitter: Jhonathanjbr
linkedin: jhonathan-ribeiro
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jhonathanribeiro.netlify.app/" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Jhonathan Ribeiro # add your name
author-img: jhonathan.png # add your photo
img-openGraph: woman-using-notebook-for-home-working.jpg
about-author: Sou desenvolvedor web focado no desenvolvimento front-end. Entusiasta de novas tecnologias Web e Mobile.

# Disqus
discus-identifier: Jhonathan Ribeiro # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 4
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
