#SEO - Meta tags values
title: Blog Jhonathan Ribeiro
description: > 
  Bem vindo ao meu blog! Aqui você encontra artigos sobre tecnologia, dicas, snippets e muito mais. Inscreva-se agora mesmo em nossa Newsletter e fique por dentro de todas as nossas novidades.
