backend:
 name: github
 repo: JhonathanRibeiro/blog

media_folder: "assets/uploads"

collections:
 - name: "blog-settings"
   label: "Blog Settings"
   files:   
      - label: "Blog Settings"
        name: "blog"
        file: "_data/site.yml"
        fields:
            - label: "Bio initial"
              name: "initbio"
              widget: "string"
            - label: "Tec Bio"
              name: "tecbio"
              widget: "string"
            - label: "Bio end"
              name: "endbio"
              widget: "string"
#A identação impacta na execução correta do código...
#new collectionn for add and edit posts on blog
 - label: "Post"
   name: "posts"
   folder: "_posts"
   create: true #permite que seja possível criar um novo post
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "postLayout"
      - label: "Autor"
        name: "author"
        widget: "string"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Descrição"
        name: "description"
        widget: "string"
      - label: "Categorias"
        name: "categories"
        widget: "string"
      - label: "Data"
        name: "date"
        widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "string"
      - label: "Imagem"
        name: "img"
        widget: "image"
      - label: "OG Title"
        name: "ogtitle"
        widget: "string"
      - label: "OG Type"
        name: "ogtype"
        widget: "string"
      - label: "OG Description"
        name: "ogdescription"
        widget: "string"
      - label: "OG Image"
        name: "ogimage"
        widget: "image"
      - label: "Body"
        name: "body"
        widget: "markdown"