backend:
 name: github
 repo: JhonathanRibeiro/blog

media_folder: "assets/img"

collections:
 - name: "Site-settings"
   label: "Site Settings"
   files:   
      - label: "Site Settings"
        name: "site"
        file: "_data/site.yml"
        fields:
            - label: "Título da página"
              name: "title"
              widget: "string"
            - label: "Descrição da página"
              name: "description"
              widget: "string"
 
 - name: "Settings author"
   label: "Settings author"
   files:   
      - label: "Settings author"
        name: "author"
        file: "_data/author.yml"
        fields:
            - label: "Nome do autor"
              name: "author"
              widget: "string"
            - label: "Foto do autor"
              name: "author-img"
              widget: "image"
            - label: "Bio do autor"
              name: "about-author"
              widget: "string"

#A identação impacta na execução correta do código...
#new collectionn for add and edit posts on blog
 - label: "Post"
   name: "posts"
   folder: "_posts"
   create: true #permite que seja possível criar um novo post
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "postLayout"
      - label: "Autor"
        name: "author"
        widget: "string"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Descrição"
        name: "description"
        widget: "string"
      - label: "Data"
        name: "date"
        widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "string"
      - label: "Imagem"
        name: "img"
        widget: "image"
      - label: "OG Title"
        name: "ogtitle"
        widget: "string"
      - label: "OG Type"
        name: "ogtype"
        widget: "string"
      - label: "OG Description"
        name: "ogdescription"
        widget: "string"
      - label: "OG Image"
        name: "ogimage"
        widget: "image"
      - label: "Body"
        name: "body"
        widget: "markdown"