backend:
 name: github
 repo: JhonathanRibeiro/blog

media_folder: "assets/img"

collections:
 - name: "Site-settings"
   label: "Site Settings"
   files:   
      - label: "Site Settings"
        name: "site"
        file: "_data/site.yml"
        fields:
            - label: "Título da página"
              name: "title"
              widget: "string"
            - label: "Descrição da página"
              name: "description"
              widget: "string"
 
 - name: "Settings author"
   label: "Settings author"
   files:   
      - label: "Settings author"
        name: "author"
        file: "_data/author.yml"
        fields:
            - label: "Nome do autor"
              name: "author"
              widget: "string"
            - label: "Foto do autor"
              name: "author-img"
              widget: "image"
            - label: "Bio do autor"
              name: "about-author"
              widget: "string"

 - name: "Settings Social Media links"
   label: "Settings Social Media"
   files:   
      - label: "Settings Links Social Media"
        name: "socialmedia"
        file: "_data/links-social-media.yml"
        fields:
            - label: "Facebook"
              name: "facebook"
              widget: "string"
            - label: "Github"
              name: "github"
              widget: "string"
            - label: "Instagram"
              name: "instagram"
              widget: "string"
            - label: "Twitter"
              name: "twitter"
              widget: "string"
            - label: "Linkedin"
              name: "linkedin"
              widget: "string"
            - label: "E-mail"
              name: "email"
              widget: "string"

#A identação impacta na execução correta do código...
#new collectionn for add and edit posts on blog
 - label: "Post"
   name: "posts"
   folder: "_posts"
   create: true #permite que seja possível criar um novo post
   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
   fields:
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        default: "post"
      - label: "Autor"
        name: "author"
        widget: "string"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Descrição"
        name: "description"
        widget: "string"
      - label: "Data"
        name: "date"
        widget: "string"
      - label: "Tags"
        name: "tags"
        widget: "string"
      - label: "Imagem"
        name: "img"
        widget: "image"
      - label: "Link da fonte"
        name: "link_font"
        widget: "string"
      - label: "Font Title"
        name: "font_title"
        widget: "string"
      - label: "OG Title"
        name: "ogtitle"
        widget: "string"
      - label: "OG Type"
        name: "ogtype"
        widget: "string"
      - label: "OG Description"
        name: "ogdescription"
        widget: "string"
      - label: "OG Image"
        name: "ogimage"
        widget: "image"
      - label: "TWITTER-Creator"
        name: "twitter-creator"
        widget: "string"
      - label: "TWITTER-Card"
        name: "twitter-card"
        widget: "string"
      - label: "TWITTER-Site"
        name: "twitter-site"
        widget: "string"
      - label: "Body"
        name: "body"
        widget: "markdown"
# Create new projects...
 - label: "Projects"
   name: "project"
   folder: "_projects"
   create: true #permite que seja possível criar um novo [projeto]
   slug: "{{slug}}"
   fields:
      - label: "Imagem"
        name: "img"
        widget: "image"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Descrição"
        name: "description"
        widget: "string"
      - label: "Site do projeto"
        name: "site-project"
        widget: "string"
# Create new service...
 - label: "Services"
   name: "service"
   folder: "_services"
   create: true #permite que seja possível criar um novo [servico]
   slug: "{{slug}}"
   fields:
      - label: "Imagem"
        name: "img"
        widget: "image"
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "Descrição"
        name: "description"
        widget: "string"
      - label: "URL do serviço"
        name: "url-service"
        widget: "string"
# Create new dica...
 - label: "References"
   name: "references"
   folder: "_references"
   create: true #permite que seja possível criar um novo [servico]
   slug: "{{slug}}"
   fields:
      - label: "Título"
        name: "title"
        widget: "string"
      - label: "ariaLabelId"
        name: "ariaLabelId"
        widget: "string"
      - label: "dataTargetId"
        name: "dataTargetId"
        widget: "string"
      - label: "Content"
        name: "body"
        widget: "markdown"